### ISSUE TITLE
Not compatible with Java 11

### ISSUE THREAD

**Issue by enver-haase** [vaadin/base-starter-flow-osgi#11]
Given Vaadin12 is compatible with Java11, this very project here should be, too.

Here is part of the log.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/home/ehaase/git/base-starter-flow-osgi/target/felix-framework-6.0.0/bin/felix.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Auto-deploy install: org.osgi.framework.BundleException: Could not create bundle object. - java.io.FileNotFoundException: META-INF/MANIFEST.MF

Test machine:
Ubuntu Linux 18.04 LTS, oracle-java8-set-default works,
oracle-java11-set-default does not; add webup8team PPA.

**Comment by mstahv** [comment]
The project runs fine but there are indeed some deprecation warnings from felix. Nothing to do with Vaadin integration, but we could see if those can be updated at some point. With JDK 15, the compilation of the project now fails: 

    [ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:4.1.0:bnd-process (default) on project project-base-osgi: bnd error: null: ConcurrentModificationException -> [Help 1]
[

**Comment by mstahv** [comment]
This PR seems to fix the issue: https://github.com/vaadin/base-starter-flow-osgi/pull/103
