### ISSUE TITLE
OSGi Starter throws exception when opening default view

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/base-starter-flow-osgi#14]
I downloaded the latest starter from vaadin.com/start and run it via the given maven command `mvn -Pprepare-osgi-container -Prun-osgi-container verify`. Started up with some error messages. When trying to access the default page, the following exception comes up:

```
[ERROR] Exception while processing request to /
javax.servlet.ServletException: com.vaadin.flow.server.ServiceException: java.lang.IllegalStateException: Exception targets has been already initialized
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:229)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
...
 ``` 

Machine is Windows 10 (Microsoft Windows [Version 10.0.17763.253])

**Comment by stefanuebe** [comment]
Full console output

[scratch.txt](https://github.com/vaadin/base-starter-flow-osgi/files/2831563/scratch.txt)

**Comment by pleku** [comment]
This is not valid anymore for the reworked base starter using bnd-tools to run itself.
