### ISSUE TITLE
Starter does not find routes (FileNotFound)

### ISSUE THREAD

**Issue by ecki** [vaadin/base-starter-flow-osgi#15]
When I install the OSGi starter with maven felix starts up, but on http://localhost.8080 it only tells me 
    
    Could not navigate to ''
    Reason: Couldn't find route for ''
    Available routes:
    This detailed message is only shown when running in development mode.

There is no error message at that time (but the startup complains about not found manifest files. I tried different maven versions, here is the transcript:

This is Win10 (german) with mvn 3.50 and openjdk 8 (Zulu 8.35 aka 8u202)

[osgilog.txt](https://github.com/vaadin/base-starter-flow-osgi/files/2833318/osgilog.txt)

Not sure if related to #14, I dont see that specified exception (and there also nothing on the web console).

**I do wonder if the errors are caused by the webjars which are no bundle and I dont see where an extender does apply?**

**Comment by ecki** [comment]
Found the problem, the Zip I downloaded does not contain the `bnd.bnd` file, which means it does not process those non-bundles mentioned above. When I manually create it, it works. (However the MANIFEST.MF FileNotFound errors still appear)

**Comment by pleku** [comment]
This is not valid anymore for the master branch of the base starter, which build on top of v19 (no webjars).
