### ISSUE TITLE
Servletpattern other then root URL pattern /* is not resolving static resources

### ISSUE THREAD

**Issue by Maurice-Betzel** [vaadin/base-starter-flow-osgi#32]
In the class VaadinServletRegistration set:

`properties.put(HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_PATTERN,"/test/*");`

results in static recources not getting found and the Button displays just text in the browser.
Changing the maven-antrun-plugin into the following does also not resolve the issue:

`
 <tasks>
                                <mkdir
                                        dir="${project.build.directory}/generated-resources/test/frontend/bower_components"></mkdir>
                                <copy
                                        todir="${project.build.directory}/generated-resources/test/frontend/bower_components">
                                    <fileset
                                            dir="${project.build.directory}/dependency/META-INF/resources/webjars/"/>
                                </copy>
                            </tasks>`

What more must be done to resolve the static content of the Vaadin components?

**Comment by Maurice-Betzel** [comment]
The HTML page displays as resource path for the Button:

<link rel="import" href="./../frontend/bower_components/vaadin-button/src/vaadin-button.html">

If i am correct this means `http://localhost/` comming from `http://localhost/test/`

**Comment by mstahv** [comment]
This issue is now solved in Vaadin 19 and newer. Solving it in older versions is so tricky that we will most likely never fix this (except via warranty).
