### ISSUE TITLE
Support for Apache Karaf / Karaf Feature

### ISSUE THREAD

**Issue by JulianFeinauer** [vaadin/base-starter-flow-osgi#72]
Just posting this here as there may be another community here. Description is copied over from https://vaadin.com/forum/thread/17845647/apache-karaf-osgi-integration-for-vaadin-flow

we are currently investigating the migration of a Vaadin Flow (currently 13.x) Application from Spring to OSGi, Apache Karaf in more detail. There is somme documentation on the Vaadin site https://vaadin.com/docs/v14/flow/osgi/tutorial-osgi-basic.html. Furthermore, I found this example App in Github https://github.com/vaadin/base-starter-flow-osgi.

The first one I dont really get but the second one (the Github Example) I am able to run. But it starts an "internal" felix server. As we like Karaf I would like to see a Karaf feature for that, but I'm not able to extract that from the Felix example. I already raised an issue on the Karaf list here: https://lists.apache.org/thread.html/ddf62343a566e0e5066c5492df8354a1229e0e09a3c76c3e1edb0e7d@%3Cuser.karaf.apache.org%3E

It would be really nice to get Vaadin and Karaf folks to cooperate on this and help each other out. Has anybody any experience with Vaadin (Flow) on Karaf?

Thanks! Julian

**Comment by caalador** [comment]
Hi.

Felix is just the container used in the profiles to run the project and doesn't lock the actual
project to it in any way as the felix dependencies are only used inside the profile `prepare-osgi-container`.

Later this year OSGi should get npm support in v14.x and also support  for Karaf and enRoute.

For progress please follow tickets 
- Fix enRoute issues and validate using it #4968
- Allow using Vaadin components as OSGi services #5125
- Add examples of #5125 vaadin/base-starter-flow-osgi#25

**Comment by JulianFeinauer** [comment]
Hi @caalador, I disagree with closing this issue as the issue still exists. Currently I am preparing a pr for a vaadin karaf feature as well as example code to deploy a vaadin app on a karaf insurance but it looks like there is very few interest in that from vaadin?
