### ISSUE TITLE
A number of missing requirements, (version>=1.2.0)(!(version>=2.0.0)) for example

### ISSUE THREAD

**Issue by enver-haase** [vaadin/base-starter-flow-osgi#9]
So far tested on OSX and Linux Ubuntu, both under Oracle Java 11.

Note that the stacktrace seems to be interwoven multi-process stderr/stdout so I only copy a small part here for the gist:

ERROR: Bundle com.vaadin.flow.component.upload [119] Error starting file:/Users/ehaase/git/base-starter-flow-osgi/target/felix-framework-6.0.0/bundle/vaadin-upload-flow-1.2.0.jar (org.osgi.framework.BundleException: Unable to resolve com.vaadin.flow.component.upload [119](R 119.0): missing requirement [com.vaadin.flow.component.upload [119](R 119.0)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component.dependency)(version>=1.2.0)(!(version>=2.0.0))) [caused by: Unable to resolve com.vaadin.flow.server [13](R 13.0): missing requirement [com.vaadin.flow.server [13](R 13.0)] osgi.wiring.package; (&(osgi.wiring.package=com.helger.css.decl)(version>=6.1.0)(!(version>=7.0.0))) [caused by: Unable to resolve com.helger.ph-css [61](R 61.0): missing requirement [com.helger.ph-css [61](R 61.0)] osgi.wiring.package; (&(osgi.wiring.package=com.helger.commons)(version>=9.0.0)(!(veorg.osgi.framework.BundleException: Unable to resolve com.vaadin.flow.component.upload [119](R 119.0): missing requirement [com.rsion>=10.0.0))) [caused by: Unable to resolve com.helger.ph-commons [60](R 60.0): missing requirement [com.helger.ph-commons [6vaadin.flow.component.upload [119](R 119.0)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component.dependency)(v0](R 60.0)] osgi.wiring.package; (osgi.wiring.package=javax.xml.bind)]]] Unresolved requirements: [[com.vaadin.flow.component.upersion>=1.2.0)(!(version>=2.0.0))) [caused by: Unable to resolve com.vaadin.flow.server [13](R 13.0): missing requirement [com.vload [119](R 119.0)] osgi.wiring.package; (&(osgi.wiring.package=com.vaadin.flow.component.dependency)(version>=1.2.0)(!(version>=2.0.0)))])

**Comment by pleku** [comment]
Fixed by using platform version `12.0.3` or newer. Fixed for `master` branch with #10
